---
- name: Install Vector
  become: yes
  become_user: root
  hosts: clickhouse
  handlers:
    - name: Start vector service
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - block:
        - name: Get vector distrib
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
            dest: "/home/centos/vector-{{ vector_version }}.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - vector-0.34.1-1.x86_64.rpm
      notify: Start vector service
    - name: Flush handlers
      meta: flush_handlers
    - name: write using jinja2
      ansible.builtin.template:
         src: ./group_vars/vector.yaml.j2
         mode: 0644
         dest: /etc/vector/vector.yaml
         owner: vector
         group: vector