---
- name: Install Vector
  become: yes
  become_user: root
  hosts: clickhouse
  handlers:
    - name: Start vector service
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - block:
        - name: Get vector distrib
          ansible.builtin.get_url:
            url: "https://yum.vector.dev/stable/vector-0/x86_64/vector-0.34.1-1.x86_64.rpm"
            dest: "./vector-0.34.1-1.x86_64.rpm"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.yum:
        name:
          - vector-0.34.1-1.x86_64.rpm
      notify: Start vector service
    - name: Flush handlers
      meta: flush_handlers
    - name: write using jinja2
      ansible.builtin.template:
         src: ./group_vars/vector.yaml.j2
         mode: 0644
         dest: /etc/vector/vector.yaml
         owner: bin
         group: wheel
    - name: Restart Vector
      become: true
      ansible.builtin.command: "systemctl restart vector"