---
# tasks file for lighthouse-role
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present
- name: Install Nginx Web Server
  yum:
    name=nginx
- name: Install git
  yum:
    name=git
- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/lighthouse
    state: absent
- name: Read-write git checkout from github
  ansible.builtin.git:
    repo: https://github.com/VKCOM/lighthouse.git
    dest: /usr/share/nginx/lighthouse
- name: write nginx.conf using jinja2
  ansible.builtin.template:
     src: nginx.conf.j2
     mode: 0644
     dest: /etc/nginx/nginx.conf
  notify:
    - nginx systemd