---
#Условия для установки Clickhouse
- name: Install Clickhouse
  become_user: root
  hosts: clickhouse-01
#Основной блок установки Clickhouse
  roles:
    - clickhouse

#Условия для установки Vector
- name: Install Vector
  become: true
  become_user: root
  hosts: vector-01
#Основной блок установки Vector
  roles:
    - vector-role

#Условия для установки Lighthouse
- name: Install nginx
  hosts: lighthouse-01
  become: true
  become_user: root
#Основной блок установки сервисов для работы Lighthouse
  roles:
    - lighthouse-role